name: Kong API Gateway Workflow  

on:
  push:
    branches:
      - main

jobs:

  OAS_TO_Kong:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      # - name: Install Insomnia CLI
      #   run: |
      #     wget https://github.com/Kong/insomnia/releases/download/lib%408.6.1/inso-linux-8.6.1.tar.xz
      #     tar -xf inso-linux-8.6.1.tar.xz

      # - name: Lint OpenAPI Spec
      #   run: |
      #     ./inso lint spec test.yaml 

      # - name: Generate kong.yaml
      #   run: ./inso generate config test.yaml --type declarative -o kong.yaml

      - name: install deck CLI
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.34.0/deck_1.34.0_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp 
          sudo cp /tmp/deck /usr/local/bin/

      # - name: update
      #   run: deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file kong.yaml --output-file new-kong.yaml

      # - name: download jq
      #   run: |
      #     sudo apt install jq -y
      #     jq --version

      # - name: download yq
      #   run: |
      #     sudo snap install yq
      #     yq --version

      - name: Set headers and run deck sync
        run: |  
              # cat new-kong.yaml
              deck file openapi2kong -s test.yaml --select-tag=dev -o kong.yaml
              deck sync  --select-tag dev -s kong.yaml --konnect-token spat_cbdDxuiAWLhjGVnKneiSOxz10au8pPqKmx6hL22cgNtheJLeA --konnect-control-plane-name Transit-testing

      
  publish-customer-api-to-portal:  # Publish the API to the dev portal
  
    name: Publish OAS to dev portal

    needs: OAS_TO_Kong   # Make sure the completed before running this job

    runs-on: ubuntu-latest  # Use Ubuntu as the operating system for the job

    steps:

      
      - name: Create API product
        run: |
          curl --request POST \
            --url https://us.api.konghq.com/v2/api-products \
            --header 'Authorization: Bearer spat_cbdDxuiAWLhjGVnKneiSOxz10au8pPqKmx6hL22cgNtheJLeA' \
            --header 'Content-Type: application/json' \
            --data '{
              "name": "test-product-pipeline",
              "description": "Creating through admin api",
              "labels": {}
            }'

      - name: Publish the product to the dev portal
        run: |
          curl --request PATCH \
            --url https://us.api.konghq.com/v2/api-products/fb44c5e6-6811-4933-916c-fca9ad2cb3e8 \
            --header 'Authorization: Bearer spat_cbdDxuiAWLhjGVnKneiSOxz10au8pPqKmx6hL22cgNtheJLeA' \
            --header 'Content-Type: application/json' \
            --data '{
              "portal_ids":["a4de9169-5d2a-494e-8411-4d44c555abd9"]
            }'

      - name: Create the product version
        run: |
          curl --request POST \
            --url https://us.api.konghq.com/v2/api-products/fb44c5e6-6811-4933-916c-fca9ad2cb3e8/product-versions \
            --header 'Authorization: Bearer spat_cbdDxuiAWLhjGVnKneiSOxz10au8pPqKmx6hL22cgNtheJLeA' \
            --header 'Content-Type: application/json' \
            --data '{
              "name": "v1",
              "publish_status": "published",
              "gateway_service": null
            }'

      - name: Link service to the product version
        run: |
          curl --request PATCH \
            --url https://us.api.konghq.com/v2/api-products/fb44c5e6-6811-4933-916c-fca9ad2cb3e8/product-versions/1b53cbe2-7e5c-4c2f-a246-46055b365314 \
            --header 'Authorization: Bearer spat_cbdDxuiAWLhjGVnKneiSOxz10au8pPqKmx6hL22cgNtheJLeA' \
            --header 'Content-Type: application/json' \
            --data '{
              "name": "v1",
              "publish_status": "published",
              "deprecated": false,
              "notify": true,
              "gateway_service": {
                "control_plane_id": "04332fa3-6402-403e-9229-478e806b7d17",
                "id": "de359fd8-c82f-4dc3-8bb1-0578c08f7903"
              }
            }'

    
  
  
          

        

   
        
   
         
    
         

     



    

        

   
        
   
         
    
         

     
