name: Kong API Gateway Workflow  

on:
  push:
    branches:
      - main

jobs:

  OAS_TO_Kong:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Insomnia CLI
        run: |
          wget https://github.com/Kong/insomnia/releases/download/lib%403.12.0/inso-linux-3.12.0.tar.xz
          tar -xf inso-linux-3.12.0.tar.xz

      - name: Lint OpenAPI Spec
        run: |
          ./inso update --self
          ./inso lint spec oas-httpbin-modified.yml --verbose 

      # - name: Generate kong.yaml
      #   run: ./inso generate config oas-httpbin-modified.yml --type declarative -o kong.yaml

      - name: install deck CLI
        run: |
          curl -sL https://github.com/kong/deck/releases/download/v1.34.0/deck_1.34.0_linux_amd64.tar.gz -o deck.tar.gz
          tar -xf deck.tar.gz -C /tmp 
          sudo cp /tmp/deck /usr/local/bin/

      # - name: update
      #   # run: deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file kong.yaml --output-file new-kong.yaml
      #   run: deck convert --from kong-gateway-2.x --to kong-gateway-3.x --input-file kong.yaml --output-file new-api.yaml

      # - name: download jq
      #   run: |
      #     sudo apt install jq -y
      #     jq --version

      # - name: download yq
      #   run: |
      #     sudo snap install yq
      #     yq --version

      - name: check
        run: |  
          cat modified-api.yaml
          deck sync -s oas-httpbin-modified.yml --kong-addr https://us.api.konghq.com/v2/control-planes/c1b32c25-8557-410c-9ea9-a3c2ca174835 --header 'Authorization: kpat_P5PCapsYVA3zlplkqkmWtuSRPRcJ5HP0xEbPvqzrGBkwZYYre'

      
      - name: Commit files
        id: commit
        run: | 
          git config --local user.email "krishna.sharma@neosalpha.com"
          git config --local user.name "krishna2507"
          git add \*.yaml
          if [-z "$(git status --porcelain)"]; then
             echo "::set-output name=push::false"
          else
             git commit -m "Add changes sd" -a
             echo "::set-output name=push::true"
          fi
        shell: bash
       
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
           github_token: ${{ secrets.GITHUB_TOKEN }}

    
  
  
          

        

   
        
   
         
    
         

     



    

        

   
        
   
         
    
         

     
